method: bayes
metric:
  name: valid_f1
  goal: maximize
parameters:
  learning_rate:
    values:
      - 0.0001
      - 0.001
      - 0.01
      - 0.1
  optimizer:
    values:
      - Adam
      - SGD
  loss:
    value: CrossEntropyLoss
  batch_size:
    values:
      - 32
      - 64
      - 128
      - 256
      - 512
  epochs:
    values:
      - 10
      - 20 
      - 50
  num_warmup_steps: 
    value: 0
  model_name: 
    value: LSTMClassifier3
  output_path:
    value: ../results
  eval_strategy:
    value: steps
  fp16:
    value: True
  dataset:
    value: combined_claim_cs
  dataset_path:
    value: ../data
  language:
    value: cs
  embedding:
    value: fasttext
  embedding_path:
    value: ./outputs/wikipedia_cs_embedding/wikipedia_cs_embedding.ft
  embedding_dim:
    value: 100
  hidden_dim:
    values:
      - 16
      - 32
      - 64
      - 128
  n_layers:
    values:
      - 1
      - 2
      - 3
  dropout:
    values:
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
  bidirectional:
    values:
      - True
      - False
  output_dim:
    value: 3
  device:
    value: cuda
  metrics:
    value:
      - name: f1
        task: multiclass
        average: macro
        num_classes: 3
      - name: accuracy
        task: multiclass
        average: macro
        num_classes: 3
      - name: precision
        task: multiclass
        average: macro
        num_classes: 3
      - name: recall
        task: multiclass
        average: macro
        num_classes: 3  

