learning_rate: 0.00005
optimizer: AdamW
loss: CrossEntropyLoss
batch_size: 32
epochs: 10
num_warmup_steps: 0
model_name: CustomBERT
output_path: ../results
eval_strategy: steps
fp16: True
dataset: combined_claim_sk
dataset_path: ../data
model_path: ./outputs/bert_model/slovaksum_sk
tokenizer_path: './embeddings/bert_tokenizer/slovaksum_sk/vocab.txt'
embedding_path: './outputs/fasttext/ud_sk_embedding/ud_sk_embedding.ft'
language: sk
output_dim: 2
device: cuda
metrics:
  - name: f1
    task: binary
    average: macro
    # num_classes: 2
  - name: accuracy
    task: binary
    average: macro
    # num_classes: 2
  - name: precision
    task: binary
    average: macro
    # num_classes: 2
  - name: recall
    task: binary
    average: macro
    # num_classes: 2