learning_rate: 0.0005
optimizer: Adam
loss: CrossEntropyLoss
batch_size: 512
epochs: 10
num_warmup_steps: 0
model_name: LSTMClassifier
output_path: ../results
eval_strategy: steps
fp16: True
dataset: liar
dataset_path: ../data
language: en
embedding: fasttext
embedding_path: ./outputs/fasttext/combined_en_embedding/combined_en_embedding.ft
embedding_dim: 100
hidden_dim: 64
n_layers: 1
dropout: 0.3
bidirectional: False
output_dim: 2
device: cuda
metrics:
  - name: f1
    task: binary
    average: macro
    # num_classes: 2
  - name: accuracy
    task: binary
    average: macro
    # num_classes: 2
  - name: precision
    task: binary
    average: macro
    # num_classes: 2
  - name: recall
    task: binary
    average: macro
    # num_classes: 2